[package]
name = "wussup"
version = "0.1.0"
authors = ["avpyatn2 <avpyatn2@mts.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
