server:
  port: 8001
  env: "dev" # "dev" | "prod"
auth:
  password: "password"
  secret: "secret"
  access_expires: 900 # 15 mins
  refresh_expires: 604800 # 7 days
log:
  appenders:
    stdout:
      kind: console
      encoder:
        pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} - {h({l})} {M} {f}:{L} = {m} {n}"
  root:
    level: error
    appenders:
      - stdout
  loggers:
    wussup_lib:
      level: debug
      appenders:
        - stdout
      additive: false