server:
  port: 8001
  env: "dev" # "dev" | "prod"
auth:
  enable: true
  password: "password"
  secret: "secret"
  access_expires: 900 # 15 mins
  refresh_expires: 604800 # 7 days
db:
  url: "postgres://postgres:password@localhost/test"
  max_connections: 16
file:
  base_path: "/tmp"
logger:
  appenders:
    stdout:
      kind: console
      encoder:
        pattern: "{d(%Y-%m-%d %H:%M:%S %Z)(utc)} - {h({l})} {M} = {m} {n}"
  root:
    level: error
    appenders:
      - stdout
  loggers:
    wussup:
      level: debug
      appenders:
        - stdout
      additive: false
    wussup_lib:
      level: debug
      appenders:
        - stdout
      additive: false